import Head from 'next/head';

import Content from '/components/content';
import MultistepForm from '/components/multistep-form';

import Text from '/data/text.mdx';

export async function getStaticProps(context) {
    const response = await fetch('https://my.backend/form-data');

    const data = await response.json();

    return {
        props: { ...data }
    };
}

export default function AdvancedForm({ steps }) {
    return (
        <div>
            <Head>
                <title>Wcag stuff - advanced form</title>
                <meta name="wcag site" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Content>
                    <div className="header">
                        <Text />
                    </div>

                    <MultistepForm steps={steps} />
                </Content>
            </main>
            <style jsx>{`
                .header {
                    margin-bottom: 4rem;
                }
            `}</style>
        </div>
    );
}
