import Head from 'next/head';
import { serialize } from 'next-mdx-remote/serialize';

import Content from '/components/content';
import Text from '/data/text.mdx';

import Markdown from '/components/markdown';

export async function getStaticProps(context) {
    const res = await fetch('https://my.backend/markdown');

    const data = await res.json();

    const md = await serialize(data);

    return {
        props: { md }
    };
}

export default function AdvancedForm({ md }) {
    return (
        <div>
            <Head>
                <title>Wcag stuff - advanced form</title>
                <meta name="wcag site" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Content>
                    <div className="header">
                        <Markdown md={md} />
                        <Text />
                    </div>
                </Content>
            </main>
            <style jsx>{``}</style>
        </div>
    );
}
