import Head from 'next/head';
import Link from 'next/link';

import Content from '/components/content';

export default function Home() {
   return (
      <div>
         <Head>
            <title>Wcag stuff</title>
            <meta name="wcag site" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <Content>
               <h1>Wcag</h1>
               <nav>
                  <li>
                     <Link href="/forms">Forms</Link>
                  </li>
                  <li>
                     <Link href="/advanced-form">Advanced form</Link>
                  </li>
               </nav>
            </Content>
         </main>
         <style jsx>{``}</style>
      </div>
   );
}
