import Head from 'next/head';
import Content from '/components/content';

export default function Home() {
   return (
      <div>
         <Head>
            <title>Wcag stuff</title>
            <meta name="wcag site" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <Content>
               <h1>Wcag</h1>
               <ul>
                  <li>
                     <a href="/forms">Forms</a>
                  </li>
               </ul>
            </Content>
         </main>
         <style jsx>{``}</style>
      </div>
   );
}
